### ISSUE TITLE
Compiling fails with ESPHome 2025.6.1

### ISSUE THREAD

**Issue by ThomPre99** [Fabian-Schmidt/esphome-ewaterlevel#4]
Hi Fabian,

first of all, thank you very much for your great work. After updating ESPHome to version 2025.6.1, compiling fails.

Here the configuration.yaml:
```
esphome:
  name: esp32-ir

esp32:
  board: esp32dev
        
external_components:
  - source: github://Fabian-Schmidt/esphome-ewaterlevel
    components: ["ewaterlevel_ble"]

logger:

api:
  encryption:
    key: "xxx"

ota:
  - platform: esphome
    password: "xxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Esp32-Ir Fallback Hotspot"
    password: !secret wifi_fallback_password
    channel: 11

captive_portal:

esp32_ble_tracker:
  scan_parameters:
    interval: 10ms
    window: 10ms
    active: false

sensor:
  - platform: ewaterlevel_ble
    id: e_waterlevel_ble
    mac_address: "xx:xx:xx:xx:xx:xx"
    min_value: 2
    max_value: 40
    height:
      name: "water_height"
    level:
      name: "water_level"
    battery_voltage:
      name: "water_battery_voltage"
    battery_level:
      name: "water_battery_level"
```

Here the logfile:
```
INFO ESPHome 2025.6.1
INFO Reading configuration /root/config/esp32-ir.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing esp32-ir (board: esp32dev; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 2.1.4
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.3.0
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- noise-c @ 0.1.6
|-- ArduinoJson @ 6.18.5
Compiling .pioenvs/esp32-ir/src/esphome/components/ewaterlevel_ble/ewaterlevel.cpp.o
Compiling .pioenvs/esp32-ir/src/esphome/components/logger/logger.cpp.o
Compiling .pioenvs/esp32-ir/src/esphome/components/logger/logger_esp32.cpp.o
Compiling .pioenvs/esp32-ir/src/esphome/components/logger/logger_esp8266.cpp.o
Compiling .pioenvs/esp32-ir/src/esphome/components/logger/logger_host.cpp.o
Compiling .pioenvs/esp32-ir/src/esphome/components/logger/logger_libretiny.cpp.o
Compiling .pioenvs/esp32-ir/src/esphome/components/logger/logger_rp2040.cpp.o
Compiling .pioenvs/esp32-ir/src/esphome/components/logger/task_log_buffer.cpp.o
Compiling .pioenvs/esp32-ir/src/esphome/components/md5/md5.cpp.o
Compiling .pioenvs/esp32-ir/src/esphome/components/mdns/mdns_component.cpp.o
src/esphome/components/ewaterlevel_ble/ewaterlevel.cpp: In member function 'virtual bool esphome::ewaterlevel_ble::EWaterLevel::parse_device(const esphome::esp32_ble_tracker::ESPBTDevice&)':
src/esphome/components/ewaterlevel_ble/ewaterlevel.cpp:48:90: error: invalid initialization of reference of type 'const esp_ble_gap_cb_param_t::ble_scan_result_evt_param&' from expression of type 'const esphome::esp32_ble::BLEScanResult'
   const esp_ble_gap_cb_param_t::ble_scan_result_evt_param &param = device.get_scan_result();
                                                                    ~~~~~~~~~~~~~~~~~~~~~~^~
*** [.pioenvs/esp32-ir/src/esphome/components/ewaterlevel_ble/ewaterlevel.cpp.o] Error 1
========================== [FAILED] Took 3.86 seconds ==========================

```

What's going wrong?

Thank you and kind regards
Thomas
